### ISSUE TITLE
Hello~, dose the multiplexer client support Block Commands ?

### ISSUE THREAD

**Issue by wxmayifei** [dahomey-technologies/rustis#40]
the commands such as blpop, brpush, xread...block  and so on 

thank you ~

**Comment by mcatanzariti** [comment]
Hi @wxmayifei,

As explained in this section of the documentation:

"Beware that using Client in a multiplexer mode, by cloning an instance across multiple threads, is not suitable for using blocking commands because they monopolize the whole connection which cannot be shared anymore."

It means you have to dedicate a single Client connection to blocking commands. However, you can also use a multiplexed client instance for non blocking commands at the same time. The only effect is that you will have multiple connections instead of a unique multiplexed connection.

Cheers,

Michaël
